# Generated by Django 2.1.7 on 2019-06-07 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_auto_20190607_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gradebox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='gradebox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quiz.GradeBox'),
            preserve_default=False,
        ),
    ]
