# Generated by Django 2.1.7 on 2019-06-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20190607_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='gradebox',
        ),
    ]
