# Generated by Django 2.1.7 on 2019-06-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_grade_gradebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='gradebox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='quiz.GradeBox'),
            preserve_default=False,
        ),
    ]
