# Generated by Django 2.1.7 on 2019-06-14 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_grade_gradebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbox',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizbox_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
