# Generated by Django 2.1.7 on 2019-06-14 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_quizbox_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizbox',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizbox_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
