# Generated by Django 2.1.7 on 2019-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190602_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='(내용없음)'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_box',
        ),
        migrations.AddField(
            model_name='message',
            name='message_box',
            field=models.ManyToManyField(related_name='messages', to='message.MessageBox'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='(제목없음)', max_length=50),
        ),
    ]
