# Generated by Django 2.2.3 on 2019-08-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190602_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_at',)},
        ),
    ]
