# Generated by Django 2.2.1 on 2019-05-29 06:31

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_articlemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='file',
            field=models.FileField(null=True, upload_to=courses.models.upload_to),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=20),
        ),
    ]
