# Generated by Django 2.2.1 on 2019-06-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190529_0631'),
        ('courses', '0004_auto_20190531_2133'),
    ]

    operations = [
    ]
