# Generated by Django 2.2.1 on 2019-06-16 10:01

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_merge_20190603_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_to),
        ),
    ]
